export const AppConstants = {
	SHOW_LOADER: 'SHOW_LOADER',
	SET_ISSUES_DATA: 'SET_ISSUES_DATA',
	SET_NEXT_SHOWN_ISSUES: 'SET_NEXT_SHOWN_ISSUES',
	SET_PREV_SHOWN_ISSUES: 'SET_PREV_SHOWN_ISSUES',
	SET_KEYMETRICS_DATA: 'SET_KEYMETRICS_DATA',
	SET_GEOSPATIAL_DATA: 'SET_GEOSPATIAL_DATA',
	FILTER_ISSUES: 'FILTER_ISSUES',
	CLEAR_FILTERS: 'CLEAR_FILTERS',
	SORT_ISSUES_BY_DATE: 'SORT_ISSUES_BY_DATE'
}